name: Manual Two Jobs

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Print JOB1
        run: echo "JOB1"

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Print JOB2
        run: echo "JOB2"
