name: Manual Two Jobs

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: job1
    steps:
      - name: Print JOB1
        run: echo "JOB1"

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    environment:
      name: job2
    steps:
      - name: Print JOB2
        run: echo "JOB2"
